package commands

type Mob string

const (
	Allay           Mob = "allay"
	Armadillo           = "armadillo"
	Axolotl             = "axolotl"
	Bat                 = "bat"
	bee                 = "bee"
	Blaze               = "blaze"
	Bogged              = "bogged"
	Breeze              = "breeze"
	Camel               = "camel"
	Cat                 = "cat"
	CaveSpider          = "cave_spider"
	Chicken             = "chicken"
	Cod                 = "cod"
	Cow                 = "cow"
	Creaking            = "creaking"
	Creeper             = "creeper"
	Dolphin             = "dolphin"
	Donkey              = "donkey"
	Drowned             = "drowned"
	ElderGuiardian      = "elder_guardian"
	EnderDragon         = "ender_dragon"
	Enderman            = "enderman"
	Endermite           = "endermite"
	Evoker              = "evoker"
	Fox                 = "fox"
	Frog                = "frog"
	Ghast               = "ghast"
	Giant               = "giant"
	GlowSquid           = "glow_squid"
	Goat                = "goat"
	Guardian            = "guardian"
	Horse               = "horse"
	Hoglin              = "hoglin"
	Husk                = "husk"
	Illusioner          = "illusioner"
	IronGolem           = "iron_golem"
	KillerBunny         = "killer_bunny"
	Llama               = "llama"
	MagmaCube           = "magma_cube"
	Mooshroom           = "mooshroom"
	Mule                = "mule"
	Ocelot              = "ocelot"
	Panda               = "panda"
	Parrot              = "parrot"
	Phantom             = "phantom"
	Pig                 = "pig"
	Piglin              = "piglin"
	PiglinBrute         = "piglin_brute"
	Pillage             = "pillager"
	PolarBear           = "polar_bear"
	Pufferfish          = "pufferfish"
	Rabbit              = "rabbit"
	Ravager             = "ravager"
	Salmon              = "salmon"
	Sheep               = "sheep"
	Shulker             = "shulker"
	Silverfish          = "silverfish"
	Skeleton            = "skeleton"
	SkeletonHorse       = "skeleton_horse"
	Slime               = "slime"
	SnowGolem           = "snow_golem"
	Sniffer             = "sniffer"
	Spider              = "spider"
	Squid               = "squid"
	Stray               = "stray"
	Strider             = "strider"
	Tadpole             = "tadpole"
	TraderLlama         = "trader_llama"
	TropicalFish        = "tropical_fish"
	Turtle              = "turtle"
	Vex                 = "vex"
	Villager            = "villager"
	Vindicator          = "vindicator"
	WanderingTrader     = "WanderingTrader"
	Warden              = "warden"
	Witch               = "witch"
	Wither              = "wither"
	WitherSkeleton      = "wither_skeleton"
	Wolf                = "wolf"
	Zoglin              = "zoglin"
	Zombie              = "zombie"
	ZombieHorse         = "zombie_horse"
	ZombieVillager      = "zombie_villager"
	ZombifiedPiglin     = "zombified_piglin"
)

type Weather string

const (
	Clear   Weather = "clear"
	Rain            = "rain"
	Thunder         = "thunder"
)

type AttributeName string

const (
	MaxHealth           AttributeName = "generic.max_health"
	MaxAbsorbtion                     = "generic.max_absorption"
	FollowRange                       = "generic.follow_range"
	KnockbackResistance               = "generic.knockback_resistance"
	MovementSpeed                     = "generic.movement_speed"
	AttackDamage                      = "generic.attack_damage"
	Armor                             = "generic.armor"
	ArmorToughness                    = "generic.armor_toughness"
	AttackKnockback                   = "generic.attack_knockback"
	AttackSpeed                       = "generic.attack_speed"
	Luck                              = "generic.luck"
)

type Difficulty string

const (
	Peaceful Difficulty = "peaceful"
	Easy                = "easy"
	Normal              = "normal"
	Hard                = "hard"
)

type Effect string

const (
	Speed            Effect = "speed"
	Slowness                = "slowness"
	Haste                   = "haste"
	MiningFatigue           = "mining_fatigue"
	Strength                = "strength"
	InstantHealth           = "instant_health"
	InstantDamage           = "instant_damage"
	JumpBoost               = "jump_boost"
	Nausea                  = "nausea"
	Regeneration            = "regeneration"
	FireResistance          = "fire_resistance"
	WaterBreathing          = "water_breathing"
	Invisibility            = "invisibility"
	Blindness               = "blindness"
	NightVision             = "night_vision"
	Hunger                  = "hunger"
	Weakness                = "weakness"
	Poison                  = "poison"
	WitherEffect            = "wither"
	HealthBoost             = "health_boost"
	Absorption              = "absorption"
	Saturation              = "saturation"
	Glowing                 = "glowing"
	Levitation              = "levitation"
	Lucky                   = "luck"
	BadLuck                 = "unluck"
	FatalPoison             = "fatal_poison"
	SlowFalling             = "slow_falling"
	ConduitPower            = "conduit_power"
	DolphinsGrace           = "dolphins_grace"
	BadOmen                 = "bad_omen"
	HeroOfTheVillage        = "hero_of_the_village"
	Darkness                = "darkness"
	Infested                = "infested"
	Oozing                  = "oozing"
	Weaving                 = "weaving"
	WindCharged             = "wind_charged"
	RaidOmen                = "raid_omen"
	TrialOmen               = "trial_omen"
)

type Enchantment string

const (
	AquaAffinity         Enchantment = "aqua_affinity"
	BaneOfArthropods                 = "bane_of_arthropods"
	BlastProtection                  = "blast_protection"
	Breach                           = "breach"
	Channeling                       = "channeling"
	Cleaving                         = "cleaving"
	CurseOfBinding                   = "binding_curse"
	CurseOfVanishing                 = "vanishing_curse"
	DepthStrider                     = "depth_strider"
	Density                          = "density"
	Efficiency                       = "efficiency"
	FeatherFalling                   = "feather_falling"
	FireAspect                       = "fire_aspect"
	FireProtection                   = "fire_protection"
	Flame                            = "flame"
	Fortune                          = "fortune"
	FrostWalker                      = "frost_walker"
	Impailing                        = "impailing"
	Infinity                         = "infinity"
	Knockback                        = "knockback"
	Looting                          = "looting"
	Loyalty                          = "loyalty"
	LuckOfTheSea                     = "luck_of_the_sea"
	Lure                             = "lure"
	Mending                          = "mending"
	Multishot                        = "multishot"
	Piercing                         = "piercing"
	Power                            = "power"
	ProjectileProtection             = "projectile_protection"
	Protection                       = "protection"
	Punch                            = "punch"
	QuickCharge                      = "quick_charge"
	Respiration                      = "respiration"
	Riptide                          = "riptide"
	Sharpness                        = "sharpness"
	SilkTouch                        = "silk_touch"
	Smite                            = "smite"
	SoulSpeed                        = "soul_speed"
	SweepingEdge                     = "sweeping_edge"
	SwiftSneak                       = "swift_sneak"
	Thorns                           = "thorns"
	Unbreaking                       = "unbreaking"
	WindBurst                        = "wind_burst"
)
